export const ReduxTypes = {
  INIT: '@@REDUX_COMMON/INIT',
  INIT_DONE: '@@REDUX_COMMON/INIT_DONE',

  GET_LIST: '@@REDUX_COMMON/GET_LIST',
  GET_LIST_DONE: '@@REDUX_COMMON/GET_LIST_DONE',
  GET_LIST_ERROR: '@@REDUX_COMMON/GET_LIST_ERROR',

  CREATE: '@@REDUX_COMMON/CREATE',
  CREATE_DONE: '@@REDUX_COMMON/CREATE_DONE',
};